create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text default '',
  body text not null,
  image_url text,
  published_at timestamptz not null default now()
);

alter table public.posts enable row level security;

create policy "public can read posts" on public.posts for select to anon, authenticated using (true);

insert into storage.buckets (id, name, public) values ('blog-images', 'blog-images', true) on conflict (id) do nothing;

create policy "public can view blog images" on storage.objects for select to anon, authenticated using (bucket_id = 'blog-images');
