'use client';
import {useEffect,useState} from 'react';

export default function Admin(){
 const [logged,setLogged]=useState(false),[password,setPassword]=useState(''),[posts,setPosts]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState({title:'',excerpt:'',body:'',image_url:''}),[msg,setMsg]=useState('');
 async function load(){const r=await fetch('/api/admin/posts'); if(r.status===401){setLogged(false);return} const d=await r.json(); if(Array.isArray(d)){setPosts(d);setLogged(true)}}
 useEffect(()=>{load()},[]);
 async function login(e){e.preventDefault();const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setPassword('');setLogged(true);load()}else setMsg('Invalid password.');}
 async function save(e){e.preventDefault();const url=editing?`/api/admin/posts/${editing.id}`:'/api/admin/posts';const r=await fetch(url,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(r.ok){setMsg('Saved.');setEditing(null);setForm({title:'',excerpt:'',body:'',image_url:''});load()}else setMsg((await r.json()).error||'Could not save.');}
 async function remove(id){if(!confirm('Delete this post?'))return;await fetch(`/api/admin/posts/${id}`,{method:'DELETE'});load()}
 async function upload(e){const file=e.target.files?.[0];if(!file)return;const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const d=await r.json();if(r.ok)setForm(f=>({...f,image_url:d.url}));else setMsg(d.error||'Upload failed.');}
 if(!logged)return <main className="adminwrap"><div className="admincard"><div className="eyebrow">Jay Tevar / Admin</div><h1 style={{fontFamily:'Space Grotesk'}}>Sign in</h1><form className="form" onSubmit={login}><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/><button className="btn primary" type="submit">Enter</button>{msg&&<div className="notice">{msg}</div>}</form></div></main>;
 return <main className="adminwrap"><div className="admincard"><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'center'}}><div><div className="eyebrow">Jay Tevar / Admin</div><h1 style={{fontFamily:'Space Grotesk'}}>Notes</h1></div><button className="btn secondary" onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});setLogged(false)}}>Log out</button></div>
 <form className="form" onSubmit={save}><label>Title</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><label>Short excerpt</label><input value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})}/><label>Article</label><textarea required value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/><label>Image</label><input type="file" accept="image/*" onChange={upload}/>{form.image_url&&<img src={form.image_url} alt="Uploaded" style={{maxWidth:220,borderRadius:8}}/>}<input placeholder="Or paste an image URL" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><div className="actions"><button className="btn primary" type="submit">{editing?'Update':'Publish'}</button>{editing&&<button type="button" className="btn secondary" onClick={()=>{setEditing(null);setForm({title:'',excerpt:'',body:'',image_url:''})}}>Cancel</button>}</div>{msg&&<div className="notice">{msg}</div>}</form>
 <div className="adminposts">{posts.map(p=><div className="adminpost" key={p.id}><div><strong>{p.title}</strong><div style={{fontSize:12,color:'#777'}}>{new Date(p.published_at).toLocaleDateString()}</div></div><div className="actions"><button className="btn secondary" onClick={()=>{setEditing(p);setForm({title:p.title,excerpt:p.excerpt||'',body:p.body,image_url:p.image_url||''})}}>Edit</button><button className="btn secondary danger" onClick={()=>remove(p.id)}>Delete</button></div></div>)}</div>
 </div></main>;
}
