const projects=[
{title:'Unscoped',type:'Featured case study',status:'Live product',description:'A lightweight change-order tool that helps independent contractors record extra work, prepare updated pricing, and communicate changes to customers.',contribution:'Problem research · Product direction · Workflow design · Copywriting · Testing · Launch',proof:'Customer problem identification, product thinking, communication, and end-to-end execution.',url:'/work/unscoped',logo:'/logos/unscoped.svg',image:'/unscoped/dashboard.png',internal:true},
{title:'Cake Sumo',type:'Product project',status:'Working product',description:'A quoting and order-planning tool designed to help custom cake businesses organize requirements and prepare clearer customer quotations.',contribution:'Product concept · Workflow planning · Feature direction · Copywriting · AI-assisted development',proof:'Niche research, process design, audience-focused communication, and digital project execution.',url:'https://cakesumo.vercel.app',logo:'/logos/cake-sumo.svg'},
{title:'Blumentritt Avenue',type:'Research + content',status:'In development',description:'A digital exploration that organizes Philippine mythology, culture, and history into a more accessible experience.',contribution:'Research · Content development · Information architecture · Visual direction · Web development',proof:'Editorial judgment, cultural storytelling, research organization, and long-form project development.',url:'https://blumentritt.vercel.app',logo:'/logos/blumentritt.svg'}];

const rolePaths=[
{number:'01',title:'Content & Marketing',summary:'I turn business objectives, research, and complex information into clear communications for internal and external audiences.',skills:['Content strategy','Copywriting and editing','Marketing communications','Scripts and presentations','SEO-informed articles','Sales materials'],roles:'Content marketing · Communications · Content operations · Copywriting · Editing'},
{number:'02',title:'Operations & Coordination',summary:'I bring structure to recurring work by documenting processes, coordinating requirements, and creating systems people can follow.',skills:['SOPs and manuals','Workflow documentation','Project coordination','Recruitment operations','Client onboarding','Process improvement'],roles:'Business operations · Project coordination · Marketing operations · Documentation'},
{number:'03',title:'Research & Business Support',summary:'I gather and organize information so teams can understand markets, opportunities, competitors, customers, and business requirements.',skills:['Market research','Competitor research','Audience research','Trend monitoring','Business development support','Research reports'],roles:'Business research · Market research · Sales enablement · Business support'}];

const experience=[
{company:'ibex',role:'Senior Content Marketing Executive',dates:'2016–Present',progression:'Business Research Analyst → Content Marketing Executive → Senior Content Marketing Executive',description:'Lead and support content across marketing, internal communications, sales materials, scripts, presentations, newsletters, executive communications, and creative projects. Research markets, clients, competitors, industries, and emerging technologies for leadership and business decisions.',proof:'Career progression · Content leadership · Research · Stakeholder support · AI-assisted workflows'},
{company:'Atomic Digital',role:'Remote Content Creator',dates:'2024–2026',description:'Produced and edited AI-assisted articles, turning initial drafts into accurate, structured, human-readable content through research, editorial judgment, SEO fundamentals, and publishing guidelines.',proof:'Remote collaboration · Editorial work · Responsible AI use · Quality control'},
{company:'HP Outsourcing',role:'Sales & Marketing Associate',dates:'2015',description:'Supported proposals, sales materials, client communications, onboarding, and the promotion of virtual-assistance services across sales, operations, account management, and business development.',proof:'Client communication · Sales support · Service marketing · Onboarding'},
{company:'Focusing Group Corporation',role:'Recruitment Manager & Operations Professional',dates:'2011–2014',progression:'VA Generalist → Operations Supervisor → Business Development Officer → Recruitment Manager',description:'Created more than 20 client-specific SOPs, manuals, training guides, and onboarding resources while handling recruitment, talent sourcing, client requirements, and internal coordination.',proof:'Career progression · Operations · Documentation · Recruitment · Business development'},
{company:'Western Wats Research',role:'Market Researcher',dates:'2008–2009',description:'Conducted structured market research with U.S. households and businesses while following research protocols, scripts, reporting requirements, and quality standards.',proof:'Research discipline · Professional communication · Accuracy · International audiences'}];

const writing=[
{type:'Editing demonstration',title:'How I Turn Rough Drafts Into Clear, Publish-Ready Content',description:'A practical before-and-after demonstration of how I identify clarity and structure problems, revise the writing, and explain the editorial decisions.',skills:'Editing · Content analysis · Clarity · Editorial judgment',url:'https://jet.home.blog/2026/03/28/how-i-turn-rough-drafts-into-clear-publish-ready-content/'},
{type:'Business thought leadership',title:'Remote Team Productivity Is Redefining What Good Management Looks Like',description:'An analysis of how remote work changes the way managers evaluate productivity, communicate expectations, and support their teams.',skills:'Business writing · Operational thinking · Long-form structure',url:'https://jet.home.blog/2026/03/10/remote-team-productivity-is-redefining-what-good-management-looks-like/'},
{type:'Marketing guide',title:'Six Steps to Craft a Strong Vision Statement',description:'A structured guide to defining, drafting, evaluating, and refining a practical vision statement for a business or brand.',skills:'Marketing knowledge · Instructional writing · Brand communication',url:'https://jet.home.blog/2024/01/21/6-steps-to-craft-a-killer-vision-statement/'}];

const emailHref='mailto:jettevar@outlook.com?subject=Employment%20Opportunity%20for%20Jay%20Tevar&body=Hi%20Jay%2C%0A%0AI%20came%20across%20your%20portfolio%20and%20would%20like%20to%20discuss%20a%20potential%20opportunity%20with%20you.';

export default function Home(){return <>
<header className="nav container"><a className="brand" href="#top">JAY TEVAR</a><nav aria-label="Primary navigation"><a href="#contribute">Expertise</a><a href="#work">Work</a><a href="#experience">Experience</a><a href="#writing">Writing</a></nav><a className="nav-cta" href={emailHref}>Contact Me About a Role</a></header>
<main id="top">
<section className="hero container"><div className="hero-copy"><div className="eyebrow">Content · Marketing · Operations · Research</div><h1>I turn unclear business needs into finished, useful work.</h1><p className="hero-lede">I’m Jay Tevar, a cross-functional marketing and operations professional with 15+ years of experience across content, research, communications, process improvement, and business support.</p><p className="hero-support">I combine professional judgment with AI and modern digital tools to research faster, communicate clearly, and move work from idea to completed deliverable.</p><div className="actions"><a className="btn primary" href={emailHref}>Contact Me About a Role <span>→</span></a><a className="btn secondary" href="#work">View My Work</a></div><p className="availability">Philippines · Remote part-time, contract, and project-based opportunities</p></div><div className="hero-visual"><div className="portrait" role="img" aria-label="Jay Tevar"/><div className="hero-note"><strong>15+ years</strong><span>of cross-functional professional experience</span></div></div></section>
<section className="proof section-tight" aria-label="Professional credibility"><div className="container proof-grid"><article><strong>15+ years</strong><span>Across marketing, content, research, operations, and business support.</span></article><article><strong>20+ resources</strong><span>Client-specific SOPs, manuals, training guides, and onboarding materials.</span></article><article><strong>4 projects</strong><span>Self-directed digital products and websites researched, directed, and built.</span></article></div></section>
<section className="section" id="contribute"><div className="container"><SectionHead eyebrow="Where I can contribute" title="Versatile, with a clear center." text="My experience crosses functions, but the work generally falls into three connected areas."/><div className="role-grid">{rolePaths.map(path=><article className="role-card" key={path.title}><span className="card-number">{path.number}</span><h3>{path.title}</h3><p>{path.summary}</p><ul>{path.skills.map(skill=><li key={skill}>{skill}</li>)}</ul><div className="role-fit"><span>Relevant areas</span>{path.roles}</div></article>)}</div></div></section>
<section className="section work" id="work"><div className="container"><SectionHead eyebrow="Selected work" title="Proof through completed output." text="Self-directed projects showing how I research problems, define solutions, communicate ideas, and produce working digital experiences."/><div className="work-list">{projects.map((project,index)=><article className={`project ${index===0?'featured':''}`} key={project.title}>{project.image&&<div className="project-image" style={{backgroundImage:`url(${project.image})`}}/>}<div className="project-content"><div className="project-top"><span>{project.type}</span><span>{project.status}</span></div><div className="project-title"><img src={project.logo} alt=""/><h3>{project.title}</h3></div><p>{project.description}</p><dl><div><dt>My contribution</dt><dd>{project.contribution}</dd></div><div><dt>What it demonstrates</dt><dd>{project.proof}</dd></div></dl><a className="text-link" href={project.url} target={project.internal?undefined:'_blank'} rel={project.internal?undefined:'noreferrer'}>{project.internal?'Read the case study':'View the project'} <span>→</span></a></div></article>)}</div><aside className="auberyn-note"><img src="/logos/auberyn.svg" alt="Auberyn"/><div><strong>Auberyn is my independent digital practice.</strong><p>It is the umbrella for my self-directed products and creative experiments—a structured environment for applying research, marketing, operations, design direction, and AI-assisted production to real projects.</p></div><a href="https://auberyn.vercel.app" target="_blank" rel="noreferrer">Visit Auberyn ↗</a></aside></div></section>
<section className="section" id="experience"><div className="container experience-layout"><div className="experience-intro"><div className="eyebrow">Professional experience</div><h2>A career built across connected disciplines.</h2><p>My career began in market research and progressed through operations, business development, recruitment, and content marketing. Each stage added a capability I use today.</p><a className="btn secondary" href="/Jay-Tevar-Resume.pdf" target="_blank">Download My Résumé</a></div><div className="timeline">{experience.map(item=><article className="timeline-item" key={`${item.company}-${item.dates}`}><div className="timeline-head"><div><h3>{item.company}</h3><p>{item.role}</p></div><span>{item.dates}</span></div>{item.progression&&<p className="progression">{item.progression}</p>}<p>{item.description}</p><div className="timeline-proof">{item.proof}</div></article>)}</div></div></section>
<section className="section writing" id="writing"><div className="container"><SectionHead eyebrow="Selected writing" title="Clear thinking, made readable." text="Examples of how I clarify information, structure ideas, adapt to audiences, and turn research into useful content."/><div className="writing-grid">{writing.map(sample=><a className="writing-card" href={sample.url} target="_blank" rel="noreferrer" key={sample.title}><span>{sample.type}</span><h3>{sample.title}</h3><p>{sample.description}</p><div>{sample.skills}</div><strong>Read the sample ↗</strong></a>)}</div></div></section>
<section className="section ai-method" id="ai-method"><div className="container method-layout"><div><div className="eyebrow">How I work with AI</div><h2>AI accelerates the work. Judgment makes it useful.</h2></div><div className="method-content"><p className="method-lede">I use AI to increase the speed and range of what I can produce—not to replace professional judgment, accountability, or collaboration.</p><ol><li><strong>Define the objective</strong><span>Understand the audience, business need, constraints, and definition of a finished deliverable.</span></li><li><strong>Accelerate the work</strong><span>Use AI to support research, explore approaches, organize information, develop drafts, or prototype practical solutions.</span></li><li><strong>Review and refine</strong><span>Evaluate the output for relevance, structure, clarity, tone, accuracy, and usefulness.</span></li><li><strong>Own the result</strong><span>Provide direction, make decisions, and follow the employer’s policies on AI, confidentiality, and approved tools.</span></li></ol></div></div></section>
<section className="section contact" id="contact"><div className="container contact-card"><div><div className="eyebrow">Let’s talk</div><h2>Looking for someone who can move the work forward?</h2><p>I’m open to remote part-time, contract, and project-based opportunities across content, marketing, operations, research, and business support.</p></div><div className="contact-actions"><a className="btn primary" href={emailHref}>Contact Me About a Role <span>→</span></a><a className="btn secondary" href="/Jay-Tevar-Resume.pdf" target="_blank">Download My Résumé</a><a href="https://www.linkedin.com/in/javinjettevar/" target="_blank" rel="noreferrer">View my LinkedIn profile ↗</a><a href="https://calendly.com/jtevar-ibex/30min" target="_blank" rel="noreferrer">Schedule a conversation ↗</a></div></div></section>
</main>
<footer className="footer"><div className="container footer-inner"><div><strong>JAY TEVAR</strong><span>Cross-functional marketing and operations professional</span></div><div><a href="mailto:jettevar@outlook.com">jettevar@outlook.com</a><span>Philippines · Available for remote opportunities</span></div><span>© 2026 Jay Tevar</span></div></footer>
</>}

function SectionHead({eyebrow,title,text}){return <div className="section-head"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div><p>{text}</p></div>}
